// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List notes
	// (GET /v1/notes)
	ListNotes(w http.ResponseWriter, r *http.Request)
	// Create a note
	// (POST /v1/notes)
	CreateNote(w http.ResponseWriter, r *http.Request)
	// Delete a note
	// (DELETE /v1/notes/{id})
	DeleteNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a note
	// (GET /v1/notes/{id})
	GetNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List users
	// (GET /v1/users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// Get current user
	// (GET /v1/users/me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List notes
// (GET /v1/notes)
func (_ Unimplemented) ListNotes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a note
// (POST /v1/notes)
func (_ Unimplemented) CreateNote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a note
// (DELETE /v1/notes/{id})
func (_ Unimplemented) DeleteNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a note
// (GET /v1/notes/{id})
func (_ Unimplemented) GetNote(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /v1/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /v1/users/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListNotes operation middleware
func (siw *ServerInterfaceWrapper) ListNotes(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNote operation middleware
func (siw *ServerInterfaceWrapper) DeleteNote(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNote operation middleware
func (siw *ServerInterfaceWrapper) GetNote(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "organization" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "organization", r.URL.Query(), &params.Organization, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organization", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/notes", wrapper.ListNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/notes", wrapper.CreateNote)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/notes/{id}", wrapper.DeleteNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/notes/{id}", wrapper.GetNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users/me", wrapper.GetMe)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RZbW/cuBH+KwO2wPUA7YvfEmc/1UkugdPEKeKk+RAYCCWOVowlUkdS6+wFC/RH9Bf2",
	"lxRDavViab3OXc79FItLzgxnnpl5hvnGEl2UWqFyli2+MYO21Mqi/zgThVQX2j3TKpXLyqCg1UQrh8rR",
	"n7wsc5lwJ7WafbFa0ZpNMiw4/fVXgylbsL/MWhWz8Kud/WKMNu9qZWyz2URMoE2MLEkYW7B/4DrJNb8G",
	"TkaARbOSCQJPEl0pB9KC0g6SxjLQClwmrd+JZso2EXvKxTv8tULrHs7u9xmCCUqh5C4DbSDWYk0WFzxP",
	"tSlQeOteaBNLIVA9nHFnlctQOZKOAuLKgVS2SlOZSFQOSjSFtFZqZb2FF9q90JV6wKhfaLBVkoFBqyuT",
	"IHltJa2McwSnwWUICc/zOr4fFK9cpo387SGR+YZcpJYUWKlWPJcCniI3aMDpa1RTRkdqaaTsmUHu8EI7",
	"7ICxL/L5L2/eLsBgigZVgrBCQ0HKweYE+v/++z8gMEeHcCNdBp8Lfo0glXSfPbzWkHElpixipdElnQ35",
	"S7ijf/ErL8oc2YIVMr+OIDbIBYuYW5e0aJ2RakkOddLRtu6Jy0yXJV03l9axiBX862tUS5exxeF8HrFC",
	"qu33wUDiJmKUC9JXjk+1+Ktmm46/YOJIcd/pA/9cOq4ENwKQ9sG2SA1vLNBxmd++c4hX3AnS2OWt466y",
	"vbPH8/ZOUjlcotnhph4U9/mh1hTd4RCCy5+FEzij2okQY67VklzjNGjVptYfxlHiIS/OPNSp5HHHFkxw",
	"hxMnCxw7IkVfw0E654fxUTI5Fic4eZQ+nk9OD54cTvhRfJyciEf4OD1lUSu8quTvhfTgTFWK7zP/VnyD",
	"JV5xFJzXdUlX/ljoP1i8IxXOoLJooDQ6lTlO4dLXSQGp0QW8+vgekpzLwsLfUm1gVuDPFPmmmfqODmf/",
	"PK9/J1n252HEsRik0RedqanQ+Pd6aZroohuAcGTEm6h4nIcC3b/KxwxdRhmZYbhUp7nzxMkVYbexnYxs",
	"rHGmwkZVrHWOXJGuVBrrLnhxK+KvdKZ2g24H8fAmnT/v6WX8KD1IDsXxBE/iR5PHp0/mEx4nYoLpweHR",
	"8ckjWrkPLHM+ZudzPZob2iy5kr/5bmbvsLi7D3guuUXbejekuwWne1f6xHhS4CTRpiQYcOMUmok2SwKn",
	"dFh4jcO8CgvcGL72OWPRqMGFtqC5X8o0MlrQDBOEKjUmlZFufUlNti5RvrgTv2m/XmyD8Orje7aLX06k",
	"tRUKSp0pvI0dlwpWksPb8+fPYFvTg0cTLRDSXN8AX3KprAt8pKWgTSAM8rwgL3sa4DHqLWrdkDlXBnIh",
	"VaqHMaUiYMF2k3srPYIyr0JcDRZ6RY7yBd12OoNvCNOmDC3YSw3/kjHCpePGoaEawCK2QmODwoPpfDr3",
	"YCtR8VKyBTuazqdHHhMu806erQ5mXhF9LHGEyLxDVxkVjOM9shl6y082WBqBwhuiyD5hyU6qPt7N54It",
	"2Gtp3YXXFPVHksP5/LuYXgPguyifb7YDTI9z+/496NTx/GCXgsb0WY8feAxXRcHNur5rLS1iji8t5UO4",
	"/NUmYqUeY4yBVFrgoZXrG0WEfr3T8UMXt7SUhVRE657WjX6Pe5v83lKD23ygxly/0TaseF84hoR50y8X",
	"VP03A2Ac/LARIOBhR/xDH/duD9Gf749+ZxD9AYAJ/qlDP4KZTdRm6uybFJsAH+KFI5TSr1vP/3TambC2",
	"EJ/CucCi1OTWBXAFlbpW+kYRr0i1QblUIAXw3Gowdfofzo+HgAuaGsD1Ync8NIyc7bEtLSy1+n85O1i9",
	"29nR3YXwDrd6CW3mcrWmzZhbBG6I+ghpnVTLStrM13jfBbbTjFZohz5+iW7cwfMHSY6HTQo6dLz/UPOK",
	"0Q/sS3R3RbXkhhfo0ND6t8EzBeFSUJFNZSiuktapU7KIBR4UOE2/anVL4B6OuLmq89hz9L0d1+/qE4Up",
	"nKfwuUsKP8OvFZo1+MtRYpVGr6RAETWpq1W+hgKLmMR55HLXI5ZTeBeuRM1njPyMPtiNt3jPctgeZ7+Q",
	"ORGWcMF4DXfQ3SYQ/pptJLo7WTcGHWLfIcGDSDwECemNffcgI5426DT45Q9k0NH+Q+1L5SZiJ/c5MfJy",
	"PEJ6qjr82+wLcGgamP95FkaK72SbdPQnu52SQaCRqy2Ppt3toEx1GPCro8kj9zU6vNQKHK2ub35nbe1Q",
	"pnq23jVQN+NyqBediXY7xtLUet9BtJ0z6+Hy1izZnf6uulNcO7rdm7f1ETxE7LPKGFSu94DxI1o0VfKk",
	"I3sMUZ2p0ZeY7rz46YoyPPy/wVgBeq0TnoPAFea6LEhL2EsTq8nrYW4xm+W0L9PWLZ6cns4ZCa3tGJvu",
	"oOCKL9HLo4FzW9baqvWhzuw/7bW41hOa3uZq878AAAD//xjX748NGgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
