// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List users
	// (GET /v1/users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// Get current user
	// (GET /v1/users/me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List users
// (GET /v1/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /v1/users/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "organization" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "organization", r.URL.Query(), &params.Organization, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organization", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/users/me", wrapper.GetMe)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xX3Y7TSBN9lVJ/n7SL5DgZZmAhVzsLCxqWPzGwXIxGom2X4wa721SXswSUd19V+yd2",
	"EgaWC+5iu7vqdNWpczpfVOqq2lm07NXyiyL0tbMew8N5Vhn73PEDZ3OzaggzeZs6y2hZfuq6Lk2q2Tg7",
	"f++dlXc+LbDS8uv/hLlaqv/Ndynm7Vc//5PI0asumdput5HK0Kdkagmmluov3KSl0x9ACwjwSGuTIug0",
	"dY1lMB6sY0gHZOAscGF8WIkUq22kHjlKTJah/Xmwzxsu0LJExwyShsFY3+S5SQ1ahhqpMt4bZ31A+Mbq",
	"hgtH5vPPrO0zgWBX4AiMXevSZPAHakICdh/Qxkq2dNEk2TTg8steuEvWNtOUAco66CkUq0jV5GokNi2f",
	"MmRtSvmFn3RVl6iWquqwJCMAKlK8qeWrZzJ2JZXyrLnxk71ni5NhobGMKyRZyYZLnCaZlPkg+DZShB8b",
	"E/h91WfqA10P613yHlMObfN4Qz3OofFIUJPLTYkxXLqGUswgJ1fBk7evIS21qTz8mjuCeYW3pBED38PQ",
	"wfnLi+67xPK3DouJ1UEt37vCxpnD37tXceoqFancUaVZLbstR4qLVidly8DpUd4WyIW0pcD2UKP50ymb",
	"NYKxA3YBOaBhanBIlThXoraSKzfk+bmu9lr0xBVH+26OoBpqFSBdPJzkVfo0P0lvZ2czvJPcnf127/5i",
	"ppM0m2F+cvv07M5deTOuStOY7FjmUh/D+dDhscWOVtqaz2Fc/Q2Ix+tAl0Z79LvqJlg6u/LAbnKkK6XT",
	"Cmepo1pooIkt0szRSshpGKuQ8QBT90IT6Y08Swp7cKCeNN+ci1ClIcaONIcDIuOKaUOGN5eiIi1h2wkX",
	"gdw9Peqb8OTta/U1C5gZ7xvMZHRieJGwNhbWRsOLi4cPoB/stqKpyxDy0v0DeqWN9RxqO3KJoRGEuqyk",
	"ykHnAkcDol0ZCua6VU9jc3fY02fa6hX60DkPfjzkw0DAZVPXjthDjpwWInQBUEMkdiBbIyiNZ/miy7IN",
	"FoG2GeSmZKSgjZsJb+JBm5bqsYO/TYJwyZoYCWbwJsA5f3mhIrVG8i3Yk3gRLwJRa7S6NmqpTuNFfBr4",
	"xEVo0Hx90qqNPKyQD4/8Crkh2x9576gXObwbw3wHHxukDdSadCWCUZNbmwyzCKiL42y5gQqrRMK5HLjQ",
	"PD0qvGoZ6EEfbePR24EUSKQyhLjI1FI9NZ5DYdr50RVyOOfV/gkfhaJ3B0w2cMPgShYje8IxVaTa2ZpI",
	"Qc8vPZ258TjvD911NL2E3V4s/tPNYNCDm64IEwM7kIrDG4PUTxrU0mMbqbPFyddyDOjnE9sNm06/vWl3",
	"adtG6s737DhyTQ0S1FSVpk2Pvunaz3oljVctHa5l5UD8eSuON3Jf5ldPbnmy9Rff+z1kSGbdK4Gs3ll+",
	"DM8d4CcWDS0hlYE3Hiqd4SFlHyM/E5n9ATIMRBtuCV+7GgzG37r1yJt7Qxb//V5L3TlmZ5N7rjj2seux",
	"H+1MaBt95yV3yuBDxj4YSWzfmh8k7oRLj5En8n2MUSP/CxIzdr6ra5nw9k/KMQF66lJdQoZrLF1dSZZ2",
	"rXgvlZ0tLefzUtYVzvPy/r17CyVBOxz7EQUWVMGsQjyxzl7WdqrVgt9eb/8NAAD//44iWacSDgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
